groups:
- name: cyberguard-ai-critical
  interval: 30s
  rules:
  # Application Health Alerts
  - alert: CyberGuardBackendDown
    expr: up{job="cyberguard-backend"} == 0
    for: 1m
    labels:
      severity: critical
      component: backend
      team: platform
    annotations:
      summary: "CyberGuard Backend is down"
      description: "Backend service {{ $labels.instance }} has been down for more than 1 minute"
      runbook_url: "https://runbooks.cyberguard.com/backend-down"
      
  - alert: CyberGuardFrontendDown
    expr: up{job="cyberguard-frontend"} == 0
    for: 2m
    labels:
      severity: critical
      component: frontend
      team: platform
    annotations:
      summary: "CyberGuard Frontend is down"
      description: "Frontend service {{ $labels.instance }} has been down for more than 2 minutes"
      runbook_url: "https://runbooks.cyberguard.com/frontend-down"

  # Database Alerts
  - alert: DatabaseConnectionFailure
    expr: postgresql_up{} == 0
    for: 1m
    labels:
      severity: critical
      component: database
      team: platform
    annotations:
      summary: "PostgreSQL database is unreachable"
      description: "Database connection has been failing for more than 1 minute"
      runbook_url: "https://runbooks.cyberguard.com/database-down"

  - alert: DatabaseSlowQueries
    expr: postgresql_slow_queries > 10
    for: 5m
    labels:
      severity: critical
      component: database
      team: platform
    annotations:
      summary: "High number of slow database queries"
      description: "{{ $value }} slow queries detected in the last 5 minutes"
      runbook_url: "https://runbooks.cyberguard.com/database-performance"

  # Infrastructure Alerts
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: critical
      component: infrastructure
      team: platform
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 90% on {{ $labels.instance }} for more than 5 minutes"
      runbook_url: "https://runbooks.cyberguard.com/high-cpu"

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.95
    for: 3m
    labels:
      severity: critical
      component: infrastructure
      team: platform
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 95% on {{ $labels.instance }} for more than 3 minutes"
      runbook_url: "https://runbooks.cyberguard.com/high-memory"

  - alert: DiskSpaceCritical
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.05
    for: 1m
    labels:
      severity: critical
      component: infrastructure
      team: platform
    annotations:
      summary: "Critical disk space shortage"
      description: "Disk space is below 5% on {{ $labels.instance }}"
      runbook_url: "https://runbooks.cyberguard.com/disk-space"

- name: cyberguard-ai-warning
  interval: 60s
  rules:
  # Performance Alerts
  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="cyberguard-backend"}[5m])) > 2
    for: 10m
    labels:
      severity: warning
      component: backend
      team: platform
    annotations:
      summary: "High response time detected"
      description: "95th percentile response time is {{ $value }}s for more than 10 minutes"
      runbook_url: "https://runbooks.cyberguard.com/performance"

  - alert: HighErrorRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
    for: 5m
    labels:
      severity: warning
      component: backend
      team: platform
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value | humanizePercentage }} for more than 5 minutes"
      runbook_url: "https://runbooks.cyberguard.com/error-rate"

  - alert: ThreatDetectionLatency
    expr: threat_detection_duration_seconds > 5
    for: 5m
    labels:
      severity: warning
      component: ml-engine
      team: data-science
    annotations:
      summary: "High threat detection latency"
      description: "Threat detection is taking {{ $value }}s, above threshold of 5s"
      runbook_url: "https://runbooks.cyberguard.com/ml-performance"

  # Resource Warnings
  - alert: ModerateMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.80
    for: 10m
    labels:
      severity: warning
      component: infrastructure
      team: platform
    annotations:
      summary: "Moderate memory usage"
      description: "Memory usage is above 80% on {{ $labels.instance }}"
      runbook_url: "https://runbooks.cyberguard.com/memory-optimization"

  - alert: DiskSpaceWarning
    expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.20
    for: 5m
    labels:
      severity: warning
      component: infrastructure
      team: platform
    annotations:
      summary: "Low disk space warning"
      description: "Disk space is below 20% on {{ $labels.instance }}"
      runbook_url: "https://runbooks.cyberguard.com/disk-cleanup"

  # Security Alerts
  - alert: UnusualThreatActivity
    expr: increase(threats_detected_total[1h]) > 100
    for: 5m
    labels:
      severity: warning
      component: security
      team: security
    annotations:
      summary: "Unusual threat activity detected"
      description: "{{ $value }} threats detected in the last hour, above normal threshold"
      runbook_url: "https://runbooks.cyberguard.com/threat-spike"

  - alert: AuthenticationFailures
    expr: increase(authentication_failures_total[5m]) > 20
    for: 2m
    labels:
      severity: warning
      component: security
      team: security
    annotations:
      summary: "High authentication failure rate"
      description: "{{ $value }} authentication failures in the last 5 minutes"
      runbook_url: "https://runbooks.cyberguard.com/auth-failures"

- name: cyberguard-ai-info
  interval: 300s
  rules:
  # Model Performance
  - alert: ModelAccuracyDrift
    expr: model_accuracy < 0.85
    for: 30m
    labels:
      severity: info
      component: ml-engine
      team: data-science
    annotations:
      summary: "Model accuracy drift detected"
      description: "Model accuracy has dropped to {{ $value }}, below 85% threshold"
      runbook_url: "https://runbooks.cyberguard.com/model-drift"

  - alert: DataIngestionRate
    expr: rate(logs_ingested_total[1h]) < 1000
    for: 15m
    labels:
      severity: info
      component: data-pipeline
      team: platform
    annotations:
      summary: "Low data ingestion rate"
      description: "Log ingestion rate is {{ $value }}/hour, below expected 1000/hour"
      runbook_url: "https://runbooks.cyberguard.com/data-pipeline"

  # Capacity Planning
  - alert: PodRestartRate
    expr: increase(kube_pod_container_status_restarts_total[1h]) > 5
    for: 10m
    labels:
      severity: info
      component: kubernetes
      team: platform
    annotations:
      summary: "High pod restart rate"
      description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last hour"
      runbook_url: "https://runbooks.cyberguard.com/pod-restarts"

  - alert: ScalingEvent
    expr: changes(kube_deployment_status_replicas[1h]) > 3
    for: 5m
    labels:
      severity: info
      component: autoscaling
      team: platform
    annotations:
      summary: "Frequent scaling events"
      description: "Deployment {{ $labels.deployment }} has scaled {{ $value }} times in the last hour"
      runbook_url: "https://runbooks.cyberguard.com/scaling-analysis"

- name: cyberguard-ai-business
  interval: 600s
  rules:
  # Business Metrics
  - alert: ActiveUserCountLow
    expr: active_users_count < 5
    for: 30m
    labels:
      severity: info
      component: business
      team: product
    annotations:
      summary: "Low active user count"
      description: "Only {{ $value }} active users in the last 30 minutes"
      runbook_url: "https://runbooks.cyberguard.com/user-engagement"

  - alert: ThreatDetectionEfficiency
    expr: threats_detected_per_hour / logs_processed_per_hour < 0.01
    for: 1h
    labels:
      severity: info
      component: effectiveness
      team: data-science
    annotations:
      summary: "Low threat detection rate"
      description: "Threat detection rate is {{ $value | humanizePercentage }}"
      runbook_url: "https://runbooks.cyberguard.com/detection-tuning"

  - alert: SystemUptime
    expr: (time() - node_boot_time_seconds) / 86400 > 90
    for: 1m
    labels:
      severity: info
      component: maintenance
      team: platform
    annotations:
      summary: "System uptime exceeds 90 days"
      description: "System has been running for {{ $value }} days, consider maintenance window"
      runbook_url: "https://runbooks.cyberguard.com/maintenance-planning" 